services:
  # Frontend Next.js Service
  - type: web
    name: jeddah-ads-frontend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://jeddah-ads-backend.onrender.com/api

  # Backend Express.js Service
  - type: web
    name: jeddah-ads-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run server"
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://jeddah-ads-frontend.onrender.com
      # SQLite database will be stored locally (data will be lost on restart)
      - key: DATABASE_PATH
        value: ./jeddah_ads.db
      # Uploads will be stored temporarily (data will be lost on restart)
      - key: UPLOADS_DIR
        value: ./uploads