services:
  # Frontend Next.js Service
  - type: web
    name: jeddah-ads-frontend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start" # Starts Next.js production server
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        # This will be the URL of your backend service on Render
        # Example: https://jeddah-ads-backend.onrender.com
        value: backend-service-url # Replace with your backend's Render URL after it's created
      # Add any other NEXT_PUBLIC_ environment variables your frontend needs

  # Backend Express.js Service
  - type: web
    name: jeddah-ads-backend
    env: node
    plan: free
    buildCommand: "npm install" # Only install dependencies for the server
    startCommand: "npm run server" # This runs 'node server/index.js'
    healthCheckPath: /api/health # Add a simple health check endpoint to your Express app
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render injects its own PORT, but good to have a default
      - key: JWT_SECRET
        generateValue: true # Let Render generate a secure secret, or set your own
      - key: DATABASE_PATH
        value: /var/data/jeddah_ads.db # Path on the persistent disk
      - key: UPLOADS_DIR
        value: /var/data/uploads # Path on the persistent disk for uploads
    disks:
      - name: data-disk
        mountPath: /var/data
        sizeGB: 1 # Smallest persistent disk size